language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t harmeetsra/docker-react -f Dockerfile.dev .


script:
  - docker run -e CI=true harmeetsra/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "docker-react"
  env: "Dockerreact-env-1"
  bucket_name: "elasticbeanstalk-eu-west-2-260875612291"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: "main"