language: generic 
sudo: required
services:
  - docker


before_install:
  - docker build -t harmeetsra/docker-react -f dockerfile.dev .


script:
  - docker run -e CI=true harmeetsra/docker-react npm run test